version: "3.8"
services:
  bot:
    build: "./whos-hodl-bot"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
  api:
    build: "./whos-hodl-database"
    ports:
      - "3003:3003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/code
    depends_on:
      - database
  database:
    image: postgres:14.1-alpine
    restart: always
  environment:
    ports:
      - "5432:5432"
    volumes:
      - "./whos-hodl-database/postgres/data:/var/lib/postgresql"
