version: "3"
services:
  bot:
    # will build ./docker/web/Dockerfile
    build: ./whos-hodl-bot
    ports:
      - "3000:3001"
    volumes:
      - .:/code
  subsubcriber:
    # will build ./docker/web/Dockerfile
    build: ./whos-hodl-subscribe
    ports:
      - "3001:3000"
    volumes:
      - .:/code
  verify:
    # will build ./docker/web/Dockerfile
    build: ./whos-hodl-verify2
    ports:
      - "3002:3000"
    volumes:
      - .:/code
  database:
    build: "./whos-hodl-database"
    ports:
      - "3003:3003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/code
