version: "3.8"
services:
  bot:
    build: "./whos-hodl-bot"
    ports:
      - "3001:3001"
    depends_on:
      - api
  api:
    build: "./whos-hodl-database"
    env_file: "./whos-hodl-database/.env"
    ports:
      - "3003:3003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
  database:
    image: postgres:14.1-alpine
    restart: always
    # environment:
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - "5432:5432"
    volumes:
      - "whos-hodl:/var/lib/postgresql/data"
volumes:
  whos-hodl:
    external: true
